export default ([
  [
    {
      type: 'textInput',
      name: 'firstName',
      value: '',
      placeholder: 'First Name',
      isRequired: true,
      isDisabled: false,
      labelTop: 'First Name',
      labelBottom: '',
      width: 'full',
      maxWidth: 'md',
    },
    {
      type: 'textInput',
      name: 'lastName',
      value: '',
      placeholder: 'Last Name',
      isRequired: false,
      isDisabled: false,
      labelTop: 'Last Name',
      labelBottom: '',
      width: 'full',
      maxWidth: 'md',
    },
    {
      type: 'select',
      name: 'gender',
      value: '',
      options: [
        {
          value: 'male',
          text: 'Male'
        },
        {
          value: 'female',
          text: 'Female'
        },
      ],
      placeholder: 'Gender',
      isRequired: true,
      isDisabled: false,
      labelTop: 'Gender',
      labelBottom: '',
      width: 'full',
      maxWidth: 'xs',
    },
    {
      type: 'divider',
      text: 'Optional below',
    },
    {
      type: 'checkbox',
      name: 'policy',
      value: false,
      isDisabled: false,
      labelTop: 'confirm policy',
      labelBottom: 'please check here if you are ok to policy',
    },
    {
      type: 'toggle',
      value: false,
      name: 'vacant',
      isDisabled: false,
      isChecked: false,
      labelTop: 'vacant',
      labelBottom: 'This is about vacancy',
    },
    {
      type: 'btnPre',
      btnType: 'next',
      text: 'Next',
      color: 'primary',
      isDisabled: false,
    },
  ],
  [
    {
      type: 'toggle',
      value: false,
      name: 'help',
      isDisabled: false,
      isChecked: false,
      labelTop: 'Need help?',
      labelBottom: 'This is about vacancy',
    },
    {
      type: 'btnPre',
      btnType: 'previous',
      text: 'Previous',
      color: 'neutral',
      isDisabled: false,
      isLoading: false,
    },
    {
      type: 'btnPre',
      btnType: 'next',
      text: 'Next',
      color: 'primary',
      isDisabled: false,
    },
  ],
  [
    {
      type: 'toggle',
      value: false,
      name: 'help',
      isDisabled: false,
      isChecked: false,
      labelTop: 'Need help?',
      labelBottom: 'This is about vacancy',
    },
    {
      type: 'btnPre',
      btnType: 'previous',
      text: 'Previous',
      color: 'neutral',
      isDisabled: false,
    },
    {
      type: 'btnPre',
      btnType: 'confirm',
      text: 'Confirm',
      color: 'primary',
      isDisabled: false,
      isLoading: false,
    },
  ]
]);